import sqlite3

DATABASE_NAME = "pychronicle.db"

connection = sqlite3.connect(DATABASE_NAME)
cursor = connection.cursor()

# ---------------------------------------
# Get Latest Session
# ---------------------------------------
cursor.execute("""
SELECT session_id
FROM variable_states
ORDER BY id DESC
LIMIT 1
""")

latest = cursor.fetchone()

if latest is None:
    print("No execution history found.")
    exit()

session_id = latest[0]

# ---------------------------------------
# Get Timeline
# ---------------------------------------
cursor.execute("""
SELECT line_number,
       variable_name,
       serialized_value
FROM variable_states
WHERE session_id = ?
ORDER BY line_number,id
""", (session_id,))

records = cursor.fetchall()

# ---------------------------------------
# Create Report
# ---------------------------------------

report = open("execution_report.txt", "w")

report.write("=" * 60 + "\n")
report.write("          PYCHRONICLE EXECUTION REPORT\n")
report.write("=" * 60 + "\n\n")

report.write(f"Session ID : {session_id}\n\n")

current_line = None

for line, variable, value in records:

    if current_line != line:
        current_line = line
        report.write(f"\nLine {line}\n")
        report.write("-" * 30 + "\n")

    report.write(f"{variable} = {value}\n")

report.write("\n")
report.write("=" * 60 + "\n")
report.write("Generated by PyChronicle\n")
report.write("=" * 60 + "\n")

report.close()

connection.close()

print("Report exported successfully!")
print("File Name : execution_report.txt")